server {
    listen 443 quic;
    listen 443 ssl;
    listen [::]:443 quic;
    listen [::]:443 ssl;
    listen 8443 ssl proxy_protocol;

    server_name forgejo.metropolis.nexus;

    ssl_certificate /etc/letsencrypt/live/forgejo.metropolis.nexus/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/forgejo.metropolis.nexus/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/forgejo.metropolis.nexus/chain.pem;

    include headers-more.d/universal.conf;
    include snippets/proxy.conf;

    more_clear_headers X-Robots-Tag;
    more_clear_headers Cross-Origin-Embedder-Policy;

    proxy_hide_header Content-Security-Policy;
    more_set_headers "Content-Security-Policy: default-src none; connect-src 'self'; img-src *; manifest-src data:; script-src-elem 'self' 'unsafe-inline'; $style_src_type7; worker-src 'self'; form-action 'self'; frame-ancestors 'none'; upgrade-insecure-requests; base-uri 'none'";

    proxy_ssl_verify on;
    proxy_ssl_name forgejo.citadel.chi01.metropolis.nexus;

    location / {
        proxy_pass https://192.168.0.121:3000;
    }
    
}