server {
    listen 443 quic;
    listen 443 ssl;
    listen [::]:443 quic;
    listen [::]:443 ssl;
    listen 8443 ssl proxy_protocol;

    server_name grist.metropolis.nexus;

    ssl_certificate /etc/letsencrypt/live/grist.metropolis.nexus/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/grist.metropolis.nexus/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/grist.metropolis.nexus/chain.pem;

    include headers-more.d/universal.conf;
    include snippets/proxy.conf;

    more_clear_headers Cross-Origin-Embedder-Policy;

    proxy_hide_header Content-Security-Policy;
    more_set_headers "Content-Security-Policy: default-src 'none'; connect-src 'self'; frame-src https://www.youtube.com; img-src 'self' data: https://i.ytimg.com; script-src-elem 'self' 'unsafe-inline' https://www.youtube.com; $style_src_type7; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests; base-uri 'self'";

    client_max_body_size 512M;
    proxy_buffering off;

    modsecurity on;
    modsecurity_rules '
        Include /etc/nginx/modsecurity.d/modsecurity.conf
        Include /etc/nginx/modsecurity.d/crs-level-1.conf
        Include /etc/nginx/modsecurity.d/crs.conf
        Include /etc/nginx/modsecurity.d/exclusions.conf
        Include /etc/nginx/modsecurity.d/coreruleset/rules/*.conf

        # Authentik Proxy
        SecRuleUpdateTargetById 920273 !ARGS:rd
        SecRuleUpdateTargetById 942460 !ARGS:rd
    ';

    location /v/unknown/locales/en.server.json {
        proxy_pass http://192.168.0.127:8484;
        include snippets/proxy.conf;
    }

    location / {
        proxy_pass http://192.168.0.127:8484;

        include headers-more.d/authentik-proxy.conf;
        include snippets/proxy.conf;

        # translate headers from the outposts back to the actual upstream
        auth_request_set $authentik_email $upstream_http_x_authentik_email;
        proxy_set_header X-authentik-email $authentik_email;
    }
    
}
