server {
    listen 443 quic;
    listen 443 ssl;
    listen [::]:443 quic;
    listen [::]:443 ssl;
    listen 8443 ssl proxy_protocol;

    server_name rmfakecloud.tommytran.io;

    ssl_certificate /etc/letsencrypt/live/rmfakecloud.tommytran.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rmfakecloud.tommytran.io/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/rmfakecloud.tommytran.io/chain.pem;

    include headers-more.d/universal.conf;
    include snippets/proxy.conf;

    client_max_body_size 512M;
    proxy_buffering off;

    modsecurity off;
    modsecurity_rules '
        Include /etc/nginx/modsecurity.d/modsecurity.conf
        Include /etc/nginx/modsecurity.d/crs.conf
        Include /etc/nginx/modsecurity.d/crs-level-1.conf
        Include /etc/nginx/modsecurity.d/exclusions.conf
        Include /etc/nginx/modsecurity.d/coreruleset/rules/*.conf
    ';

    location / {
        proxy_pass http://192.168.0.128:3000;
    }
    
}