server {
    listen 443 quic;
    listen 443 ssl;
    listen [::]:443 quic;
    listen [::]:443 ssl;
    listen 8443 ssl proxy_protocol;

    server_name sentry.metropolis.nexus;

    ssl_certificate /etc/letsencrypt/live/sentry.metropolis.nexus/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sentry.metropolis.nexus/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/sentry.metropolis.nexus/chain.pem;

    include headers-more.d/universal.conf;
    include snippets/proxy.conf;

    modsecurity off;
    modsecurity_rules '
        Include /etc/nginx/modsecurity.d/modsecurity.conf
        Include /etc/nginx/modsecurity.d/crs.conf
        Include /etc/nginx/modsecurity.d/crs-level-1.conf
        Include /etc/nginx/modsecurity.d/exclusions.conf
        Include /etc/nginx/modsecurity.d/coreruleset/rules/*.conf
    ';

    location ~ ^/api/[0-9]+/(envelope|minidump|security|store|unreal)/ {
        more_set_headers "Access-Control-Allow-Origin: *";
        more_set_headers "Access-Control-Allow-Credentials: false";
        more_set_headers "Access-Control-Allow-Methods: GET,POST,PUT";
        more_set_headers "Access-Control-Allow-Headers: sentry-trace,baggage";
        more_set_headers "Access-Control-Expose-Headers: sentry-trace,headers";
        proxy_pass http://192.168.0.125:9000;
    }

    location / {
        proxy_pass http://192.168.0.125:9000;
    }

}