server {
    listen 443 quic;
    listen 443 ssl;
    listen [::]:443 quic;
    listen [::]:443 ssl;
    listen 8443 ssl proxy_protocol;

    server_name pdf.metropolis.nexus;

    ssl_certificate /etc/letsencrypt/live/stirling-pdf.metropolis.nexus/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stirling-pdf.metropolis.nexus/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/stirling-pdf.metropolis.nexus/chain.pem;

    include headers-more.d/universal.conf;
    include snippets/proxy.conf;

    more_clear_headers X-Robots-Tag;
    more_clear_headers Cross-Origin-Embedder-Policy;

    proxy_hide_header Content-Security-Policy;
    more_set_headers "Content-Security-Policy: default-src 'none'; connect-src 'self' blob: data:; img-src 'self' blob:; manifest-src 'self'; script-src 'unsafe-eval'; script-src-elem 'self' 'unsafe-inline'; style-src-elem 'self' 'unsafe-inline'; worker-src 'self' blob:; form-action 'none'; frame-ancestors 'none'; upgrade-insecure-requests; base-uri 'self'";

    client_max_body_size 100M;

    modsecurity on;
    modsecurity_rules '
        Include /etc/nginx/modsecurity.d/modsecurity.conf
        Include /etc/nginx/modsecurity.d/crs.conf
        Include /etc/nginx/modsecurity.d/crs-level-4.conf
        Include /etc/nginx/modsecurity.d/exclusions.conf
        Include /etc/nginx/modsecurity.d/coreruleset/rules/*.conf

        # Level 4
        SecRuleUpdateTargetById 920272 !REQUEST_BODY
        SecRuleUpdateTargetById 920273 !REQUEST_BODY
        SecRuleUpdateTargetById 942432 !ARGS:endpoint

        # Disable rules for bookmarks
        SecRuleUpdateTargetByTag OWASP_CRS !ARGS:bookmarkData

        # Disable rules for passwords
        SecRuleUpdateTargetByTag OWASP_CRS !ARGS:json.password

        # Authentik Proxy
        SecRuleUpdateTargetById 920273 !ARGS:rd
        SecRuleUpdateTargetById 942460 !ARGS:rd
    ';

    location /manifest.json {
        proxy_pass http://192.168.2.108:8080;
    }

    location / {
        proxy_pass http://192.168.2.108:8080;
        include headers-more.d/authentik-proxy.conf;
    }

}

server {
    listen 443 quic;
    listen 443 ssl;
    listen [::]:443 quic;
    listen [::]:443 ssl;
    listen 8443 ssl proxy_protocol;

    server_name stirling-pdf.metropolis.nexus;

    ssl_certificate /etc/letsencrypt/live/stirling-pdf.metropolis.nexus/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stirling-pdf.metropolis.nexus/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/stirling-pdf.metropolis.nexus/chain.pem;

    location / {
        return 308 https://pdf.metropolis.nexus$request_uri;
    }

}
